Repository aksonov/react-native-tableview, pull requests merged in 2019-08, with the labels that each got.

#205 fix: Refactor code from componentWillReceiveProps
  src/TableView.js
Labels: Bug Fix

#206 2.6.1
  README.md
  example/android/app/build.gradle
  example/android/app/src/main/java/com/tableviewdemo/MainActivity.java
  example/android/app/src/main/java/com/tableviewdemo/MainApplication.java
  example/android/settings.gradle
  example/ios/TableViewDemo.xcodeproj/project.pbxproj
  example/package.json
  example/src/screens/Example4.js
  example/src/screens/Example6.js
  example/src/screens/Example7.js
  example/src/screens/Example8.js
  example/src/screens/Home.js
  example/yarn.lock
  package.json
  src/TableView.js
Labels: RELEASE

#203 Use `RCTComponentEvent` for React Native 0.60
  RNTableView/RNTableViewManager.m
Labels: enhancement

#209 3.0.0
  README.md
  RNTableView/RNTableViewManager.m
Labels: RELEASE
